name: Publish Release

on:
  release:
    types: [published]

jobs:
  deploy-docker:
    name: Build and publish docker containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, i386, armv7, aarch64]
        build_type: ["hassio", "docker"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python3 gen.py
      - name: Set up env variables
        run: |
          tag="${GITHUB_REF#v}"
          if [[ "${{ matrix.build_type }}" == "hassio" ]]; then
            build_to="esphome/esphome-hassio-base-${{ matrix.arch }}"
            dockerfile="build/${{ matrix.arch }}/Dockerfile.hassio"
          else
            build_to="esphome/esphome-base-${{ matrix.arch }}"
            dockerfile="build/${{ matrix.arch }}/Dockerfile"
          fi

          # Set env variables so these values don't need to be calculated again
          echo "::set-env name=TAG::${tag}"
          echo "::set-env name=BUILD_TO::${build_to}"
          echo "::set-env name=IMAGE::${build_to}:${tag}"
          echo "::set-env name=DOCKERFILE::${dockerfile}"
      - name: Register QEMU binfmt
        run: docker run --rm --privileged multiarch/qemu-user-static:5.0.0-2 --reset -p yes
      - run: |
          docker build \
            --tag "${IMAGE}" \
            --file "${DOCKERFILE}" \
            .
      - name: Log in to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
      - run: docker push "${IMAGE}"
      - run: |
          docker tag "${IMAGE}" "${BUILD_TO}:latest"
          docker push "${BUILD_TO}:latest"

  deploy-lint:
    name: Build and publish lint docker container
    needs: [deploy-docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Register QEMU binfmt
        run: docker run --rm --privileged multiarch/qemu-user-static:5.0.0-2 --reset -p yes
      - run: |
          docker build \
            --tag "esphome/esphome-lint-base:latest" \
            --file "Dockerfile.lint" \
            --build-arg BUILD_FROM=esphome/esphome-base-amd64:latest \
            .
      - name: Log in to docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
      - run: docker push "esphome/esphome-lint-base:latest"
      - run: |
          tag="${GITHUB_REF#v}"
          docker tag esphome/esphome-lint-base:latest "esphome/esphome-lint-base:${tag}"
          docker push "esphome/esphome-lint-base:${tag}"

  deploy-docker-manifest:
    runs-on: ubuntu-latest
    needs: [deploy-docker]
    strategy:
      matrix:
        build_type: ["hassio", "docker"]
    steps:
    - name: Enable experimental manifest support
      run: |
        mkdir -p ~/.docker
        echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json
    - name: Log in to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
    - name: "Create the manifest"
      run: |
        TAG="dev"

        if [[ "${{ matrix.build_type }}" == "hassio" ]]; then
          base="esphome/esphome-hassio-base"
        else
          base="esphome/esphome-base"
        fi

        docker manifest create ${base}:${TAG} \
          ${base}-aarch64:${TAG} \
          ${base}-amd64:${TAG} \
          ${base}-armv7:${TAG} \
          ${base}-i386:${TAG}
        docker manifest push ${base}:${TAG}

        docker manifest create ${base}:latest \
          ${base}-aarch64:latest \
          ${base}-amd64:latest \
          ${base}-armv7:latest \
          ${base}-i386:latest
        docker manifest push ${base}:latest
