name: Publish dev releases to docker hub

on:
  push:
    branches:
    - main

jobs:
  deploy-docker:
    name: Build and publish docker containers
    if: github.repository == 'esphome/esphome-docker-base'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armv7, aarch64]
        build_type: ["ha-addon", "docker", "lint"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set TAG
      run: |
        TAG="${GITHUB_SHA:0:7}"
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Run docker base build
      run: |
        ./build.py \
          --tag "${TAG}"
          --arch "${{ matrix.arch }}"
          --build-type "docker"
          build
      if: ${{ matrix.build_type == 'lint' }}

    - name: Run build
      run: |
        ./build.py \
          --tag "${TAG}"
          --arch "${{ matrix.arch }}"
          --build-type "${{ matrix.build_type }}"
          build

    - name: Log in to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

    - name: Run push
      run: |
        ./build.py \
          --tag "${TAG}"
          --arch "${{ matrix.arch }}"
          --build-type "${{ matrix.build_type }}"
          push

  deploy-docker-manifest:
    if: github.repository == 'esphome/esphome-docker-base'
    runs-on: ubuntu-latest
    needs: [deploy-docker]
    strategy:
      matrix:
        build_type: ["ha-addon", "docker", "lint"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set TAG
      run: |
        TAG="${GITHUB_SHA:0:7}"
        echo "TAG=${TAG}" >> $GITHUB_ENV
    - name: Enable experimental manifest support
      run: |
        mkdir -p ~/.docker
        echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json

    - name: Log in to docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

    - name: Run manifest
      run: |
        ./build.py \
          --tag "${TAG}"
          --build-type "${{ matrix.build_type }}"
          manifest
